# **Finding the best combination of SMA_S & SMA_L for SMA Strategy Backtesting**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

In [ ]:
company="BEL.NS"
start_date="2023-01-01"
end_date="2026-01-06"
data=yf.download(company,start_date,end_date)
df=pd.DataFrame(data["Close"])
short_terms=7
long_terms=20
df

/tmp/ipython-input-1952847335.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data=yf.download(company,start_date,end_date)
[*********************100%***********************]  1 of 1 completed

Ticker          BEL.NS
Date
2023-01-02   96.772736
2023-01-03   96.869263
2023-01-04   95.324768
2023-01-05   96.483131
2023-01-06   95.517822
...                ...
2025-12-30  393.299988
2025-12-31  399.600006
2026-01-01  397.700012
2026-01-02  403.149994
2026-01-05  413.799988

[745 rows x 1 columns]

**Defining the function that will test the strategy for all combinations of SMA_S & SMA_L**

In [ ]:
def test_strategy(sma_combination):     # taking tuple as a argument
  df["SMA_S"]=df["BEL.NS"].rolling(window=sma_combination[0]).mean()
  df["SMA_L"]=df["BEL.NS"].rolling(window=sma_combination[1]).mean()
  df["Signal"]=np.where(df["SMA_S"]>df["SMA_L"],1,-1)
  df["LR"]=np.log(df["BEL.NS"]/df["BEL.NS"].shift(1))
  df["Strategy"]=df["Signal"].shift(1)*df["LR"]
  df.dropna(inplace=True)
  return np.exp(df["Strategy"].sum())
  # return df

In [ ]:
test_strategy((7,20))

np.float64(0.9771523073112068)

**Creating Multiple combinations of SMA_S & SMA_L for test_strategy function**

In [ ]:
from itertools import product
combination=list(product(range(1,50,1),range(15,252,1)))
result=[]
for i in combination:
  result.append(test_strategy(i))
all_result=pd.DataFrame(data=combination,columns=["SMA_S","SMA_L"])
all_result["Performance"]=result
all_result.nlargest(5,"Performance")

    SMA_S  SMA_L  Performance
9       1     24     2.343825
0       1     15     2.213095
4       1     19     2.115935
3       1     18     2.082042
10      1     25     2.033086

11613