# **First Intuition on Iterative Backtesting**

**Importing libraries, data, and find the spread**

In [15]:
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

In [16]:
companies=["COCHINSHIP.NS","BDL.NS","FORTIS.NS"]
data=yf.download(companies,period="1y",interval="1d")
df=pd.DataFrame(data["Close"])
df_spread=pd.DataFrame(data["High"]-data["Low"])
sma_s=5;sma_l=20
for i in companies:
  df[f"Spread {i}"]=df_spread[i]
  df[f"LR {i}"]=np.log(df[i]/df[i].shift(1))
  # for bar in range(1,10):
  #   print(bar,i,df.index[bar].date(),df[i].iloc[bar],df[f"Spread {i}"].iloc[bar],sep="|")
  df[f"SMA_S {i}"]=df[i].rolling(sma_s).mean()
  df[f"SMA_L {i}"]=df[i].rolling(sma_l).mean()
df.dropna(inplace=True)
Position=0
df

/tmp/ipython-input-2338589238.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data=yf.download(companies,period="1y",interval="1d")
[*********************100%***********************]  3 of 3 completed

Ticker,BDL.NS,COCHINSHIP.NS,FORTIS.NS,Spread COCHINSHIP.NS,LR COCHINSHIP.NS,SMA_S COCHINSHIP.NS,SMA_L COCHINSHIP.NS,Spread BDL.NS,LR BDL.NS,SMA_S BDL.NS,SMA_L BDL.NS,Spread FORTIS.NS,LR FORTIS.NS,SMA_S FORTIS.NS,SMA_L FORTIS.NS
Date,,,,,,,,,,,,,,,
2025-02-18,1009.442322,1230.451782,603.236572,64.561405,0.015216,1252.789233,1374.516089,81.666971,-0.059631,1095.498206,1187.244669,20.775478,-0.015607,608.800000,623.227942
2025-02-19,1047.876831,1294.365601,602.387573,145.910737,0.050639,1252.669678,1365.681555,109.705753,0.037368,1078.624402,1175.350735,12.335387,-0.001408,606.512708,621.589877
2025-02-20,1032.982788,1294.664429,609.179565,41.446774,0.000231,1252.609888,1357.945093,24.090367,-0.014316,1052.774841,1165.177615,19.626751,0.011212,606.133154,621.282742
2025-02-21,1009.192383,1319.124146,618.618347,63.614837,0.018716,1270.095288,1354.179156,64.124126,-0.023300,1034.192322,1155.640451,19.526894,0.015375,609.229492,622.651120
2025-02-24,1011.141602,1297.852661,597.892883,48.769680,-0.016257,1287.291724,1349.044086,59.326015,0.001930,1022.127185,1145.827182,24.121497,-0.034077,606.262988,623.520090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-01-19,1507.300049,1506.400024,892.049988,23.599976,-0.013320,1529.820020,1596.275006,28.900024,-0.006019,1514.680005,1501.364996,10.350037,-0.004920,903.280005,905.119998
2026-01-20,1453.099976,1436.900024,856.450012,85.900024,-0.047235,1507.740015,1585.780005,59.500000,-0.036621,1500.800000,1502.449994,41.600037,-0.040726,892.970007,902.862500
2026-01-21,1419.199951,1467.300049,844.150024,71.000000,0.020936,1494.320020,1576.680005,52.900024,-0.023606,1481.919995,1499.349994,25.450012,-0.014466,879.810010,899.935001
2026-01-22,1451.199951,1498.199951,841.450012,42.000000,0.020840,1487.080005,1569.125000,31.800049,0.022297,1469.439990,1497.849994,27.349976,-0.003204,866.110010,896.872501
2026-01-23,1408.000000,1488.400024,844.000000,30.000000,-0.006563,1479.440015,1560.940002,53.500000,-0.030221,1447.759985,1494.354993,25.150024,0.003026,855.620007,893.952499

In [17]:
df_spread

Ticker          BDL.NS  COCHINSHIP.NS  FORTIS.NS
Date
2025-01-23  111.272047      62.552755  19.576884
2025-01-24   65.249084      54.056666  26.768330
2025-01-27   45.475149      62.503020  25.669655
2025-01-28  106.988601     102.250561  18.977557
2025-01-29   47.766267      43.622820  53.286954
...                ...            ...        ...
2026-01-19   28.900024      23.599976  10.350037
2026-01-20   59.500000      85.900024  41.600037
2026-01-21   52.900024      71.000000  25.450012
2026-01-22   31.800049      42.000000  27.349976
2026-01-23   53.500000      30.000000  25.150024

[252 rows x 3 columns]

In [18]:
for i in companies:
  for j in range(len(df)):
    if df[f"SMA_S {i}"].iloc[j]>df[f"SMA_L {i}"].iloc[j]:
      if Position in [0,-1]:
        print(f"{df.index[j].date()} | {df[i]}: go Long | Price: {df[i].iloc[j]} | Spread: {df[f"Spread {i}"].iloc[j]}")
        Position=1
    elif df[f"SMA_S {i}"].iloc[j]<df[f"SMA_L {i}"].iloc[j]:
      if Position in [0,1]:
        print(f"{df.index[j].date()}: go Long| Price: {df[i].iloc[j]} | Spread: {df[f"Spread {i}"].iloc[j]}")
        Position=-1

2025-02-18: go Long| Price: 1230.4517822265625 | Spread: 64.56140531897563
2025-03-10 | Date
2025-02-18    1230.451782
2025-02-19    1294.365601
2025-02-20    1294.664429
2025-02-21    1319.124146
2025-02-24    1297.852661
                 ...
2026-01-19    1506.400024
2026-01-20    1436.900024
2026-01-21    1467.300049
2026-01-22    1498.199951
2026-01-23    1488.400024
Name: COCHINSHIP.NS, Length: 233, dtype: float64: go Long | Price: 1296.656982421875 | Spread: 61.77166693023241
2025-04-09: go Long| Price: 1354.891845703125 | Spread: 65.25877954285079
2025-04-17 | Date
2025-02-18    1230.451782
2025-02-19    1294.365601
2025-02-20    1294.664429
2025-02-21    1319.124146
2025-02-24    1297.852661
                 ...
2026-01-19    1506.400024
2026-01-20    1436.900024
2026-01-21    1467.300049
2026-01-22    1498.199951
2026-01-23    1488.400024
Name: COCHINSHIP.NS, Length: 233, dtype: float64: go Long | Price: 1444.4608154296875 | Spread: 44.73466939828904
2025-05-12: go Long| Price: 1515.1993408203125 | Spread: 33.874786910736475
2025-05-13 | Date
2025-02-18    1230.451782
2025-02-19    1294.365601
2025-02-20    1294.664429
2025-02-21    1319.124146
2025-02-24    1297.852661
                 ...
2026-01-19    1506.400024
2026-01-20    1436.900024
2026-01-21    1467.300049
2026-01-22    1498.199951
2026-01-23    1488.400024
Name: COCHINSHIP.NS, Length: 233, dtype: float64: go Long | Price: 1571.1923828125 | Spread: 57.28824477597891
2025-06-27: go Long| Price: 2036.671630859375 | Spread: 103.31816961903678
2025-09-04 | Date
2025-02-18    1230.451782
2025-02-19    1294.365601
2025-02-20    1294.664429
2025-02-21    1319.124146
2025-02-24    1297.852661
                 ...
2026-01-19    1506.400024
2026-01-20    1436.900024
2026-01-21    1467.300049
2026-01-22    1498.199951
2026-01-23    1488.400024
Name: COCHINSHIP.NS, Length: 233, dtype: float64: go Long | Price: 1670.0269775390625 | Spread: 84.68696887359874
2025-09-09: go Long| Price: 1623.4990234375 | Spread: 39.155318130412525
2025-09-15 | Date
2025-02-18    1230.451782
2025-02-19    1294.365601
2025-02-20    1294.664429
2025-02-21    1319.124146
2025-02-24    1297.852661
                 ...
2026-01-19    1506.400024
2026-01-20    1436.900024
2026-01-21    1467.300049
2026-01-22    1498.199951
2026-01-23    1488.400024
Name: COCHINSHIP.NS, Length: 233, dtype: float64: go Long | Price: 1803.60009765625 | Spread: 77.8187873755071
2025-10-09: go Long| Price: 1781.052490234375 | Spread: 29.431464205129487
2025-10-28 | Date
2025-02-18    1230.451782
2025-02-19    1294.365601
2025-02-20    1294.664429
2025-02-21    1319.124146
2025-02-24    1297.852661
                 ...
2026-01-19    1506.400024
2026-01-20    1436.900024
2026-01-21    1467.300049
2026-01-22    1498.199951
2026-01-23    1488.400024
Name: COCHINSHIP.NS, Length: 233, dtype: float64: go Long | Price: 1806.69287109375 | Spread: 31.52668308118541
2025-10-31: go Long| Price: 1785.342529296875 | Spread: 25.939595284559346
2025-12-25 | Date
2025-02-18    1230.451782
2025-02-19    1294.365601
2025-02-20    1294.664429
2025-02-21    1319.124146
2025-02-24    1297.852661
                 ...
2026-01-19    1506.400024
2026-01-20    1436.900024
2026-01-21    1467.300049
2026-01-22    1498.199951
2026-01-23    1488.400024
Name: COCHINSHIP.NS, Length: 233, dtype: float64: go Long | Price: 1649.300048828125 | Spread: 0.0
2026-01-09: go Long| Price: 1569.0 | Spread: 75.800048828125
2025-03-10 | Date
2025-02-18    1009.442322
2025-02-19    1047.876831
2025-02-20    1032.982788
2025-02-21    1009.192383
2025-02-24    1011.141602
                 ...
2026-01-19    1507.300049
2026-01-20    1453.099976
2026-01-21    1419.199951
2026-01-22    1451.199951
2026-01-23    1408.000000
Name: BDL.NS, Length: 233, dtype: float64: go Long | Price: 1142.9384765625 | Spread: 48.83025667672018
2025-06-13: go Long| Price: 1899.23291015625 | Spread: 100.05968409400248
2025-07-02 | Date
2025-02-18    1009.442322
2025-02-19    1047.876831
2025-02-20    1032.982788
2025-02-21    1009.192383
2025-02-24    1011.141602
                 ...
2026-01-19    1507.300049
2026-01-20    1453.099976
2026-01-21    1419.199951
2026-01-22    1451.199951
2026-01-23    1408.000000
Name: BDL.NS, Length: 233, dtype: float64: go Long | Price: 1974.402587890625 | Spread: 49.180089772789415
2025-07-14: go Long| Price: 1823.363525390625 | Spread: 36.185458061349664
2025-09-15 | Date
2025-02-18    1009.442322
2025-02-19    1047.876831
2025-02-20    1032.982788
2025-02-21    1009.192383
2025-02-24    1011.141602
                 ...
2026-01-19    1507.300049
2026-01-20    1453.099976
2026-01-21    1419.199951
2026-01-22    1451.199951
2026-01-23    1408.000000
Name: BDL.NS, Length: 233, dtype: float64: go Long | Price: 1604.0521240234375 | Spread: 55.27772386144534
2025-09-30: go Long| Price: 1493.199951171875 | Spread: 54.0999755859375
2025-10-23 | Date
2025-02-18    1009.442322
2025-02-19    1047.876831
2025-02-20    1032.982788
2025-02-21    1009.192383
2025-02-24    1011.141602
                 ...
2026-01-19    1507.300049
2026-01-20    1453.099976
2026-01-21    1419.199951
2026-01-22    1451.199951
2026-01-23    1408.000000
Name: BDL.NS, Length: 233, dtype: float64: go Long | Price: 1514.800048828125 | Spread: 42.5999755859375
2025-10-31: go Long| Price: 1529.9000244140625 | Spread: 35.9000244140625
2025-11-03 | Date
2025-02-18    1009.442322
2025-02-19    1047.876831
2025-02-20    1032.982788
2025-02-21    1009.192383
2025-02-24    1011.141602
                 ...
2026-01-19    1507.300049
2026-01-20    1453.099976
2026-01-21    1419.199951
2026-01-22    1451.199951
2026-01-23    1408.000000
Name: BDL.NS, Length: 233, dtype: float64: go Long | Price: 1536.5999755859375 | Spread: 26.0
2025-11-04: go Long| Price: 1481.0999755859375 | Spread: 61.7000732421875
2025-11-14 | Date
2025-02-18    1009.442322
2025-02-19    1047.876831
2025-02-20    1032.982788
2025-02-21    1009.192383
2025-02-24    1011.141602
                 ...
2026-01-19    1507.300049
2026-01-20    1453.099976
2026-01-21    1419.199951
2026-01-22    1451.199951
2026-01-23    1408.000000
Name: BDL.NS, Length: 233, dtype: float64: go Long | Price: 1613.800048828125 | Spread: 50.2000732421875
2025-11-25: go Long| Price: 1462.4000244140625 | Spread: 32.2000732421875
2025-12-26 | Date
2025-02-18    1009.442322
2025-02-19    1047.876831
2025-02-20    1032.982788
2025-02-21    1009.192383
2025-02-24    1011.141602
                 ...
2026-01-19    1507.300049
2026-01-20    1453.099976
2026-01-21    1419.199951
2026-01-22    1451.199951
2026-01-23    1408.000000
Name: BDL.NS, Length: 233, dtype: float64: go Long | Price: 1477.9000244140625 | Spread: 43.699951171875
2026-01-20: go Long| Price: 1453.0999755859375 | Spread: 59.5
2025-03-05 | Date
2025-02-18    603.236572
2025-02-19    602.387573
2025-02-20    609.179565
2025-02-21    618.618347
2025-02-24    597.892883
                 ...
2026-01-19    892.049988
2026-01-20    856.450012
2026-01-21    844.150024
2026-01-22    841.450012
2026-01-23    844.000000
Name: FORTIS.NS, Length: 233, dtype: float64: go Long | Price: 660.7186279296875 | Spread: 43.44861725614726
2025-03-17: go Long| Price: 597.59326171875 | Spread: 13.384195988787837
2025-03-24 | Date
2025-02-18    603.236572
2025-02-19    602.387573
2025-02-20    609.179565
2025-02-21    618.618347
2025-02-24    597.892883
                 ...
2026-01-19    892.049988
2026-01-20    856.450012
2026-01-21    844.150024
2026-01-22    841.450012
2026-01-23    844.000000
Name: FORTIS.NS, Length: 233, dtype: float64: go Long | Price: 652.4284057617188 | Spread: 23.172606697821607
2025-09-26: go Long| Price: 932.75 | Spread: 15.25
2025-10-01 | Date
2025-02-18    603.236572
2025-02-19    602.387573
2025-02-20    609.179565
2025-02-21    618.618347
2025-02-24    597.892883
                 ...
2026-01-19    892.049988
2026-01-20    856.450012
2026-01-21    844.150024
2026-01-22    841.450012
2026-01-23    844.000000
Name: FORTIS.NS, Length: 233, dtype: float64: go Long | Price: 989.6500244140625 | Spread: 29.4000244140625
2025-10-29: go Long| Price: 1055.449951171875 | Spread: 12.6500244140625
2025-12-23 | Date
2025-02-18    603.236572
2025-02-19    602.387573
2025-02-20    609.179565
2025-02-21    618.618347
2025-02-24    597.892883
                 ...
2026-01-19    892.049988
2026-01-20    856.450012
2026-01-21    844.150024
2026-01-22    841.450012
2026-01-23    844.000000
Name: FORTIS.NS, Length: 233, dtype: float64: go Long | Price: 901.5999755859375 | Spread: 21.85003662109375
2026-01-15: go Long| Price: 909.9500122070312 | Spread: 0.0